# Generated by Django 3.1.7 on 2021-05-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20210521_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cate',
            field=models.CharField(blank=True, choices=[('Review', '영화리뷰'), ('Mavel', '마블관'), ('Nolan', '놀란관'), ('Koeran', '한국영화관')], max_length=50),
        ),
    ]
