# Generated by Django 3.1.7 on 2021-05-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20210521_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rank',
            field=models.IntegerField(blank=True),
        ),
    ]
