# Generated by Django 3.1.7 on 2021-05-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20210521_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cate',
            field=models.CharField(blank=True, choices=[(1, 'Review'), (2, 'Mavel'), (3, 'Nolan'), (4, 'Koeran')], max_length=50),
        ),
    ]
