# Generated by Django 3.1.7 on 2021-05-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20210521_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='cate',
            field=models.CharField(blank=True, choices=[('Review', '영화리뷰'), ('Marvel', '마블관'), ('Nolan', '놀란관'), ('Korean', '한국영화관')], max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='rank',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
