# Generated by Django 3.1.7 on 2021-05-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20210521_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='youtube_link',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='cate',
            field=models.CharField(blank=True, choices=[('Review', '영화리뷰'), ('Marvle', '마블관'), ('Nolan', '놀란관'), ('Korean', '한국영화관')], max_length=50),
        ),
    ]
