# Generated by Django 3.1.7 on 2021-05-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_ids', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField(blank=True, default=False)),
                ('backdrop_path', models.CharField(blank=True, max_length=100)),
                ('movie_id', models.IntegerField(blank=True)),
                ('original_language', models.CharField(blank=True, max_length=100)),
                ('original_title', models.CharField(blank=True, max_length=100)),
                ('overview', models.TextField(blank=True)),
                ('popularity', models.FloatField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=100)),
                ('release_date', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('video', models.BooleanField(blank=True, default=False)),
                ('vote_average', models.FloatField(blank=True)),
                ('vote_count', models.IntegerField(blank=True)),
                ('genre_ids', models.ManyToManyField(blank=True, to='movies.Genre')),
            ],
        ),
    ]
